# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install Playwright system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       libnss3 libatk1.0-0 libatk-bridge2.0-0 libcairo2 libdbus-1-3 libexpat1 libfontconfig1 \
       libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libstdc++6 libx11-6 libxcomposite1 \
       libxdamage1 libxext6 libxfixes3 libxrender1 libxrandr2 libxss1 libxtst6 fonts-liberation \
       libasound2 libgbm1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy package files
COPY README.md pyproject.toml test_client.py ./
COPY src src

# Install package and dependencies
RUN pip install --no-cache-dir . mcp>=1.3.0 playwright>=1.50.0

# Install Playwright browsers
RUN playwright install chromium

ENTRYPOINT ["playwright-mcp"]
CMD []
